// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PerformancePower.Api.Data;

#nullable disable

namespace PerformancePower.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PerformancePower.Api.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("PerformancePower.Api.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "admin"
                        },
                        new
                        {
                            Id = 7,
                            Name = "superadmin"
                        });
                });

            modelBuilder.Entity("PerformancePower.Api.Models.SiteSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SiteSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "hero_type",
                            Type = "string",
                            UpdatedAt = new DateTime(2026, 5, 9, 17, 6, 42, 733, DateTimeKind.Utc).AddTicks(9869),
                            Value = "none"
                        },
                        new
                        {
                            Id = 2,
                            Key = "hero_youtube_url",
                            Type = "string",
                            UpdatedAt = new DateTime(2026, 5, 9, 17, 6, 42, 734, DateTimeKind.Utc).AddTicks(403),
                            Value = ""
                        },
                        new
                        {
                            Id = 3,
                            Key = "hero_start_time",
                            Type = "int",
                            UpdatedAt = new DateTime(2026, 5, 9, 17, 6, 42, 734, DateTimeKind.Utc).AddTicks(404),
                            Value = "0"
                        },
                        new
                        {
                            Id = 4,
                            Key = "hero_overlay_opacity",
                            Type = "int",
                            UpdatedAt = new DateTime(2026, 5, 9, 17, 6, 42, 734, DateTimeKind.Utc).AddTicks(405),
                            Value = "50"
                        },
                        new
                        {
                            Id = 5,
                            Key = "hero_title",
                            Type = "string",
                            UpdatedAt = new DateTime(2026, 5, 9, 17, 6, 42, 734, DateTimeKind.Utc).AddTicks(405),
                            Value = "Your Powersports Destination"
                        },
                        new
                        {
                            Id = 6,
                            Key = "hero_title_accent",
                            Type = "string",
                            UpdatedAt = new DateTime(2026, 5, 9, 17, 6, 42, 734, DateTimeKind.Utc).AddTicks(406),
                            Value = "Destination"
                        },
                        new
                        {
                            Id = 7,
                            Key = "hero_subtitle",
                            Type = "string",
                            UpdatedAt = new DateTime(2026, 5, 9, 17, 6, 42, 734, DateTimeKind.Utc).AddTicks(407),
                            Value = "ATVs, UTVs, Dirt Bikes, Snowmobiles & More"
                        },
                        new
                        {
                            Id = 8,
                            Key = "hero_btn1_label",
                            Type = "string",
                            UpdatedAt = new DateTime(2026, 5, 9, 17, 6, 42, 734, DateTimeKind.Utc).AddTicks(408),
                            Value = "Browse Inventory"
                        },
                        new
                        {
                            Id = 9,
                            Key = "hero_btn1_link",
                            Type = "string",
                            UpdatedAt = new DateTime(2026, 5, 9, 17, 6, 42, 734, DateTimeKind.Utc).AddTicks(409),
                            Value = "/inventory"
                        },
                        new
                        {
                            Id = 10,
                            Key = "hero_btn2_label",
                            Type = "string",
                            UpdatedAt = new DateTime(2026, 5, 9, 17, 6, 42, 734, DateTimeKind.Utc).AddTicks(410),
                            Value = "Contact Us"
                        },
                        new
                        {
                            Id = 11,
                            Key = "hero_btn2_link",
                            Type = "string",
                            UpdatedAt = new DateTime(2026, 5, 9, 17, 6, 42, 734, DateTimeKind.Utc).AddTicks(410),
                            Value = "/contact"
                        },
                        new
                        {
                            Id = 12,
                            Key = "contact_phone",
                            Type = "string",
                            UpdatedAt = new DateTime(2026, 5, 9, 17, 6, 42, 734, DateTimeKind.Utc).AddTicks(411),
                            Value = ""
                        },
                        new
                        {
                            Id = 13,
                            Key = "contact_email",
                            Type = "string",
                            UpdatedAt = new DateTime(2026, 5, 9, 17, 6, 42, 734, DateTimeKind.Utc).AddTicks(412),
                            Value = ""
                        },
                        new
                        {
                            Id = 14,
                            Key = "contact_address",
                            Type = "string",
                            UpdatedAt = new DateTime(2026, 5, 9, 17, 6, 42, 734, DateTimeKind.Utc).AddTicks(412),
                            Value = ""
                        },
                        new
                        {
                            Id = 15,
                            Key = "business_hours",
                            Type = "json",
                            UpdatedAt = new DateTime(2026, 5, 9, 17, 6, 42, 734, DateTimeKind.Utc).AddTicks(413),
                            Value = "{}"
                        },
                        new
                        {
                            Id = 16,
                            Key = "social_facebook",
                            Type = "string",
                            UpdatedAt = new DateTime(2026, 5, 9, 17, 6, 42, 734, DateTimeKind.Utc).AddTicks(423),
                            Value = ""
                        },
                        new
                        {
                            Id = 17,
                            Key = "social_instagram",
                            Type = "string",
                            UpdatedAt = new DateTime(2026, 5, 9, 17, 6, 42, 734, DateTimeKind.Utc).AddTicks(424),
                            Value = ""
                        },
                        new
                        {
                            Id = 18,
                            Key = "social_youtube",
                            Type = "string",
                            UpdatedAt = new DateTime(2026, 5, 9, 17, 6, 42, 734, DateTimeKind.Utc).AddTicks(424),
                            Value = ""
                        },
                        new
                        {
                            Id = 19,
                            Key = "seo_title",
                            Type = "string",
                            UpdatedAt = new DateTime(2026, 5, 9, 17, 6, 42, 734, DateTimeKind.Utc).AddTicks(425),
                            Value = "PerformancePower Powersports"
                        },
                        new
                        {
                            Id = 20,
                            Key = "seo_description",
                            Type = "string",
                            UpdatedAt = new DateTime(2026, 5, 9, 17, 6, 42, 734, DateTimeKind.Utc).AddTicks(426),
                            Value = "ATVs, UTVs, Dirt Bikes, Snowmobiles & More"
                        },
                        new
                        {
                            Id = 21,
                            Key = "announcement_enabled",
                            Type = "bool",
                            UpdatedAt = new DateTime(2026, 5, 9, 17, 6, 42, 734, DateTimeKind.Utc).AddTicks(426),
                            Value = "false"
                        },
                        new
                        {
                            Id = 22,
                            Key = "announcement_text",
                            Type = "string",
                            UpdatedAt = new DateTime(2026, 5, 9, 17, 6, 42, 734, DateTimeKind.Utc).AddTicks(427),
                            Value = ""
                        },
                        new
                        {
                            Id = 23,
                            Key = "about_content",
                            Type = "string",
                            UpdatedAt = new DateTime(2026, 5, 9, 17, 6, 42, 734, DateTimeKind.Utc).AddTicks(428),
                            Value = ""
                        },
                        new
                        {
                            Id = 24,
                            Key = "theme_primary_color",
                            Type = "string",
                            UpdatedAt = new DateTime(2026, 5, 9, 17, 6, 42, 734, DateTimeKind.Utc).AddTicks(428),
                            Value = "#e53935"
                        },
                        new
                        {
                            Id = 25,
                            Key = "theme_logo_url",
                            Type = "string",
                            UpdatedAt = new DateTime(2026, 5, 9, 17, 6, 42, 734, DateTimeKind.Utc).AddTicks(429),
                            Value = ""
                        },
                        new
                        {
                            Id = 26,
                            Key = "octane_embed_url",
                            Type = "string",
                            UpdatedAt = new DateTime(2026, 5, 9, 17, 6, 42, 734, DateTimeKind.Utc).AddTicks(430),
                            Value = ""
                        },
                        new
                        {
                            Id = 27,
                            Key = "synchrony_url",
                            Type = "string",
                            UpdatedAt = new DateTime(2026, 5, 9, 17, 6, 42, 734, DateTimeKind.Utc).AddTicks(430),
                            Value = ""
                        },
                        new
                        {
                            Id = 28,
                            Key = "lender_synchrony_description",
                            Type = "string",
                            UpdatedAt = new DateTime(2026, 5, 9, 17, 6, 42, 734, DateTimeKind.Utc).AddTicks(431),
                            Value = "Synchrony offers competitive rates and flexible terms for powersports financing."
                        },
                        new
                        {
                            Id = 29,
                            Key = "lender_octane_description",
                            Type = "string",
                            UpdatedAt = new DateTime(2026, 5, 9, 17, 6, 42, 734, DateTimeKind.Utc).AddTicks(431),
                            Value = "Octane specializes in powersports lending with a quick pre-qualification."
                        },
                        new
                        {
                            Id = 32,
                            Key = "maps_embed_url",
                            Type = "string",
                            UpdatedAt = new DateTime(2026, 5, 9, 17, 6, 42, 734, DateTimeKind.Utc).AddTicks(432),
                            Value = ""
                        });
                });

            modelBuilder.Entity("PerformancePower.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("MfaEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("TotpSecret")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PerformancePower.Api.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Msrp")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("SoldAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SpecSheetUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Specs")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StockNumber")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Trim")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Vin")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StockNumber")
                        .IsUnique();

                    b.HasIndex("Vin");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("PerformancePower.Api.Models.VehicleHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NewValues")
                        .HasColumnType("longtext");

                    b.Property<string>("OldValues")
                        .HasColumnType("longtext");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleHistories");
                });

            modelBuilder.Entity("PerformancePower.Api.Models.VehicleImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleImages");
                });

            modelBuilder.Entity("PerformancePower.Api.Models.RefreshToken", b =>
                {
                    b.HasOne("PerformancePower.Api.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PerformancePower.Api.Models.User", b =>
                {
                    b.HasOne("PerformancePower.Api.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PerformancePower.Api.Models.VehicleHistory", b =>
                {
                    b.HasOne("PerformancePower.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("PerformancePower.Api.Models.Vehicle", "Vehicle")
                        .WithMany("History")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("PerformancePower.Api.Models.VehicleImage", b =>
                {
                    b.HasOne("PerformancePower.Api.Models.Vehicle", "Vehicle")
                        .WithMany("Images")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("PerformancePower.Api.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PerformancePower.Api.Models.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("PerformancePower.Api.Models.Vehicle", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
