// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PowersportsApi.Data;

#nullable disable

namespace PowersportsApi.Migrations
{
    [DbContext(typeof(PowersportsDbContext))]
    [Migration("20260302044814_AddInventoryFields")]
    partial class AddInventoryFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PowersportsApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9451),
                            Description = "All-Terrain Vehicles for work and recreation",
                            IsActive = true,
                            Name = "ATV",
                            UpdatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9452)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9453),
                            Description = "Motorcycles designed for off-road terrain",
                            IsActive = true,
                            Name = "Dirtbike",
                            UpdatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9454)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9455),
                            Description = "Utility Task Vehicles for heavy-duty work",
                            IsActive = true,
                            Name = "UTV",
                            UpdatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9455)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9457),
                            Description = "Winter vehicles for snow terrain",
                            IsActive = true,
                            Name = "Snowmobile",
                            UpdatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9457)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9458),
                            Description = "Safety gear and accessories",
                            IsActive = true,
                            Name = "Gear",
                            UpdatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9458)
                        });
                });

            modelBuilder.Entity("PowersportsApi.Models.CategoryImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ThumbnailPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .IsUnique();

                    b.ToTable("CategoryImages");
                });

            modelBuilder.Entity("PowersportsApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9556),
                            Description = "Powerful 4WD ATV perfect for trail riding and utility work. Features a 686cc engine with reliable Ultramatic transmission.",
                            ImageUrl = "https://images.unsplash.com/photo-1558618047-6c0c841469ed?w=400&h=300&fit=crop",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Yamaha Grizzly 700",
                            Price = 12999.99m,
                            UpdatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9557)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9559),
                            Description = "Championship-winning motocross bike with advanced suspension and lightweight aluminum frame. Built for competition.",
                            ImageUrl = "https://images.unsplash.com/photo-1558577452-838b5e2b6b75?w=400&h=300&fit=crop",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Honda CRF450R",
                            Price = 9899.99m,
                            UpdatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9559)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9561),
                            Description = "High-performance side-by-side UTV with sport suspension and powerful ProStar engine. Ready for extreme terrain.",
                            ImageUrl = "https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=400&h=300&fit=crop",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Polaris RZR XP 1000",
                            Price = 21999.99m,
                            UpdatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9561)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9563),
                            Description = "Premium racing snowmobile with 850 E-TEC engine and advanced RAS X suspension for precise handling on trails.",
                            ImageUrl = "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Ski-Doo MXZ X-RS",
                            Price = 16499.99m,
                            UpdatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9564)
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9565),
                            Description = "Professional-grade motocross helmet with MIPS technology and superior ventilation. DOT and ECE certified.",
                            ImageUrl = "https://images.unsplash.com/photo-1558618542-b3d9f7c05de4?w=400&h=300&fit=crop",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Fox Racing V3 Helmet",
                            Price = 649.99m,
                            UpdatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9565)
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9567),
                            Description = "Turbocharged side-by-side with industry-leading power and innovative Intelligent Throttle Control.",
                            ImageUrl = "https://images.unsplash.com/photo-1591737622611-b6c5ae78542d?w=400&h=300&fit=crop",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Can-Am Maverick X3",
                            Price = 24999.99m,
                            UpdatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9567)
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9569),
                            Description = "Lightweight 4-stroke motocross bike with championship-proven performance and advanced WP XACT suspension.",
                            ImageUrl = "https://images.unsplash.com/photo-1606768666853-403c90a981ad?w=400&h=300&fit=crop",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "KTM 250 SX-F",
                            Price = 8999.99m,
                            UpdatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9570)
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9571),
                            Description = "Mountain snowmobile with revolutionary Alpha rear suspension and powerful 800 H.O. engine for deep snow performance.",
                            ImageUrl = "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Arctic Cat Alpha One",
                            Price = 15299.99m,
                            UpdatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9571)
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9573),
                            Description = "Premium motocross boots with advanced protection system and lightweight microfiber construction.",
                            ImageUrl = "https://images.unsplash.com/photo-1544966503-7cc5ac882d5b?w=400&h=300&fit=crop",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Alpinestars Tech 10 Boots",
                            Price = 599.99m,
                            UpdatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9573)
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9575),
                            Description = "Versatile utility ATV with electric power steering and independent rear suspension. Perfect for work and recreation.",
                            ImageUrl = "https://images.unsplash.com/photo-1558618047-6c0c841469ed?w=400&h=300&fit=crop",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Honda Foreman 520",
                            Price = 8999.99m,
                            UpdatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9575)
                        });
                });

            modelBuilder.Entity("PowersportsApi.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductId", "IsMain");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("PowersportsApi.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("PowersportsApi.Models.SiteSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("LastModifiedBy");

                    b.ToTable("SiteSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Company Info",
                            CreatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9598),
                            Description = "The main company name displayed throughout the website",
                            DisplayName = "Company Name",
                            IsActive = true,
                            IsRequired = true,
                            Key = "company.name",
                            SortOrder = 1,
                            Type = 0,
                            UpdatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9598),
                            Value = "PowerSports Showcase"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Company Info",
                            CreatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9601),
                            Description = "Brief tagline or motto displayed in headers and hero sections",
                            DisplayName = "Company Tagline",
                            IsActive = true,
                            IsRequired = false,
                            Key = "company.tagline",
                            SortOrder = 2,
                            Type = 0,
                            UpdatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9602),
                            Value = "Your Gateway to Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Contact Info",
                            CreatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9603),
                            Description = "Main contact email address",
                            DisplayName = "Contact Email",
                            IsActive = true,
                            IsRequired = true,
                            Key = "contact.email",
                            SortOrder = 1,
                            Type = 3,
                            UpdatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9604),
                            Value = "info@powersportsshowcase.com"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Contact Info",
                            CreatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9606),
                            Description = "Primary phone number for customer contact",
                            DisplayName = "Contact Phone",
                            IsActive = true,
                            IsRequired = true,
                            Key = "contact.phone",
                            SortOrder = 2,
                            Type = 4,
                            UpdatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9606),
                            Value = "(555) 123-4567"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Contact Info",
                            CreatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9609),
                            Description = "Physical business address",
                            DisplayName = "Business Address",
                            IsActive = true,
                            IsRequired = false,
                            Key = "contact.address",
                            SortOrder = 3,
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9609),
                            Value = "123 Adventure Lane, Outdoor City, OC 12345"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Footer",
                            CreatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9611),
                            Description = "Copyright notice displayed in the footer",
                            DisplayName = "Copyright Text",
                            IsActive = true,
                            IsRequired = true,
                            Key = "footer.copyright",
                            SortOrder = 1,
                            Type = 0,
                            UpdatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9611),
                            Value = "© 2026 PowerSports Showcase. All rights reserved."
                        },
                        new
                        {
                            Id = 7,
                            Category = "Homepage",
                            CreatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9612),
                            Description = "Main heading on the homepage hero section",
                            DisplayName = "Homepage Hero Title",
                            IsActive = true,
                            IsRequired = true,
                            Key = "homepage.hero.title",
                            SortOrder = 1,
                            Type = 0,
                            UpdatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9613),
                            Value = "Discover Your Next Adventure"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Homepage",
                            CreatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9614),
                            Description = "Subtitle text below the hero title",
                            DisplayName = "Homepage Hero Subtitle",
                            IsActive = true,
                            IsRequired = false,
                            Key = "homepage.hero.subtitle",
                            SortOrder = 2,
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 3, 2, 4, 48, 13, 589, DateTimeKind.Utc).AddTicks(9615),
                            Value = "Premium powersports vehicles and gear for every adventure seeker"
                        });
                });

            modelBuilder.Entity("PowersportsApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmailVerificationToken")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("EmailVerificationTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastLoginIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<bool>("SubscribeNewsletter")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PowersportsApi.Models.CategoryImage", b =>
                {
                    b.HasOne("PowersportsApi.Models.Category", "Category")
                        .WithOne("CategoryImage")
                        .HasForeignKey("PowersportsApi.Models.CategoryImage", "CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PowersportsApi.Models.Product", b =>
                {
                    b.HasOne("PowersportsApi.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PowersportsApi.Models.ProductImage", b =>
                {
                    b.HasOne("PowersportsApi.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PowersportsApi.Models.RefreshToken", b =>
                {
                    b.HasOne("PowersportsApi.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PowersportsApi.Models.SiteSetting", b =>
                {
                    b.HasOne("PowersportsApi.Models.User", "LastModifiedByUser")
                        .WithMany()
                        .HasForeignKey("LastModifiedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LastModifiedByUser");
                });

            modelBuilder.Entity("PowersportsApi.Models.Category", b =>
                {
                    b.Navigation("CategoryImage");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("PowersportsApi.Models.Product", b =>
                {
                    b.Navigation("ProductImages");
                });

            modelBuilder.Entity("PowersportsApi.Models.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
