// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PowersportsApi.Data;

#nullable disable

namespace PowersportsApi.Migrations
{
    [DbContext(typeof(PowersportsDbContext))]
    [Migration("20260318130000_SeedHeroVideoSettings")]
    partial class SeedHeroVideoSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Snapshot intentionally omitted — this migration only inserts seed data.
        }
    }
}
